#ifndef ADS1299_REGISTERS_H
#define ADS1299_REGISTERS_H

/* TI SBAS499C, sections 9.5 / 9.6. No STM32 or application dependencies. */
enum {
    ADS_CMD_WAKEUP = 0x02, ADS_CMD_STANDBY = 0x04,
    ADS_CMD_RESET = 0x06, ADS_CMD_START = 0x08, ADS_CMD_STOP = 0x0a,
    ADS_CMD_RDATAC = 0x10, ADS_CMD_SDATAC = 0x11,
    ADS_CMD_RDATA = 0x12, ADS_CMD_RREG = 0x20, ADS_CMD_WREG = 0x40
};
enum {
    ADS_REG_ID, ADS_REG_CONFIG1, ADS_REG_CONFIG2, ADS_REG_CONFIG3,
    ADS_REG_LOFF, ADS_REG_CH1SET, ADS_REG_CH2SET, ADS_REG_CH3SET,
    ADS_REG_CH4SET, ADS_REG_CH5SET, ADS_REG_CH6SET, ADS_REG_CH7SET,
    ADS_REG_CH8SET, ADS_REG_BIAS_SENSP, ADS_REG_BIAS_SENSN,
    ADS_REG_LOFF_SENSP, ADS_REG_LOFF_SENSN, ADS_REG_LOFF_FLIP,
    ADS_REG_LOFF_STATP, ADS_REG_LOFF_STATN, ADS_REG_GPIO,
    ADS_REG_MISC1, ADS_REG_MISC2, ADS_REG_CONFIG4, ADS_REG_COUNT
};
#define ADS_CONFIG1_RESERVED 0x90u
#define ADS_CONFIG1_MULTIPLE_READBACK 0x40u /* DAISY_EN=1; no CLK output. */
#define ADS_CONFIG2_RESERVED 0xc0u
#define ADS_CONFIG2_INT_CAL 0x10u /* CAL_AMP=0, CAL_FREQ=0: fCLK / 2^21. */
#define ADS_CONFIG3_RESERVED 0x60u
#define ADS_CONFIG3_REF_ON 0x80u
#define ADS_CONFIG3_BIASREF_INT 0x08u
#define ADS_CONFIG3_BIAS_ON 0x04u
#define ADS_CH_SRB2 0x08u
#define ADS_MUX_NORMAL 0u
#define ADS_MUX_SHORT 1u
#define ADS_MUX_TEST 5u
#define ADS_MISC1_SRB1 0x20u

#endif
