from pathlib import Path
import struct
import sys
import unittest
from unittest.mock import patch, MagicMock
import io
import tempfile
import zlib

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "host"))
from eeg_receiver import StreamDecoder, Continuity, HEADER
import eeg_receiver


def fix_crc(packet):
    struct.pack_into("<I", packet, 1016, zlib.crc32(packet[:1016]))
    return bytes(packet)


class ProtocolTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Generated by the actual firmware's portable C packet builder.
        cls.raw = (ROOT / "build" / "eeg_reference.bin").read_bytes()

    def test_c_reference(self):
        self.assertEqual(len(self.raw), 1024)
        self.assertEqual(HEADER.size, 44)
        p = StreamDecoder().feed(self.raw)[0]
        self.assertEqual((p.flags, p.count, p.stream_id, p.first_timestamp_us), (10, 36, 0x12345678, 123456789))
        self.assertEqual(p.sample_rate, 250)
        samples = list(p.samples())
        self.assertEqual(samples[0][4], (0, 1, 8388607, -8388608, -1, -2, 0x123456, -74566))
        self.assertEqual(samples[0][2], "recorded_irq")
        self.assertEqual(samples[1][1], 123460789)
        self.assertEqual(samples[1][2], "estimated")

    def test_every_split(self):
        for cut in range(1025):
            d = StreamDecoder()
            packets = d.feed(self.raw[:cut]) + d.feed(self.raw[cut:])
            self.assertEqual(len(packets), 1, cut)
        d = StreamDecoder()
        self.assertEqual(sum(len(d.feed(bytes([b]))) for b in self.raw), 1)

    def test_sticky_and_embedded_markers(self):
        modified = bytearray(self.raw)
        modified[80:84] = b"EEG1"
        modified[90:94] = b"\r\n\xa5\x5a"
        modified = fix_crc(modified)
        self.assertEqual(len(StreamDecoder().feed(self.raw + modified + self.raw)), 3)

    def test_corruption_resync(self):
        for offset in (4, 5, 8, 10, 12, 14, 200, 1016, 1020):
            corrupt = bytearray(self.raw)
            corrupt[offset] ^= 0x80
            d = StreamDecoder()
            result = d.feed(b"garbage" + corrupt + self.raw)
            self.assertEqual(len(result), 1, offset)
            self.assertGreater(d.discarded_bytes, 0)

    def test_partial_and_zero_padding(self):
        data = bytearray(self.raw)
        struct.pack_into("<H", data, 6, 11)
        struct.pack_into("<H", data, 12, 1)
        data[71:1016] = bytes(945)
        self.assertEqual(StreamDecoder().feed(fix_crc(data))[0].count, 1)
        data[71] = 1
        d = StreamDecoder()
        self.assertFalse(d.feed(fix_crc(data)))
        self.assertEqual(d.padding_errors, 1)

    def test_wrap_and_gaps(self):
        d = StreamDecoder(); tracking = Continuity()
        p = bytearray(self.raw)
        struct.pack_into("<I", p, 16, 0xffffffff)
        struct.pack_into("<I", p, 20, 0xfffffff0)
        tracking.accept(d.feed(fix_crc(p))[0])
        struct.pack_into("<I", p, 16, 0)
        struct.pack_into("<I", p, 20, 20)
        tracking.accept(d.feed(fix_crc(p))[0])
        self.assertEqual((tracking.packet_gaps, tracking.sample_gaps), (0, 0))
        struct.pack_into("<I", p, 16, 2)
        struct.pack_into("<I", p, 20, 60)
        tracking.accept(d.feed(fix_crc(p))[0])
        self.assertEqual((tracking.packet_gaps, tracking.sample_gaps), (1, 4))
        struct.pack_into("<I", p, 40, 999)
        tracking.accept(d.feed(fix_crc(p))[0])
        self.assertEqual(tracking.reorders, 0)

    def test_receiver_reconnect_discards_partial(self):
        first, second = MagicMock(), MagicMock()
        first.__enter__.return_value = first
        second.__enter__.return_value = second
        first.recv.side_effect = [self.raw[:150], b""]
        second.recv.side_effect = [self.raw[:333], self.raw[333:], b""]
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "samples.csv"
            with patch.object(sys, "argv", ["receiver", "--retries", "1", "--retry-delay", "0", "--csv", str(output)]), \
                 patch.object(eeg_receiver.socket, "create_connection", side_effect=[first, second]) as connect, \
                 patch("sys.stdout", new_callable=io.StringIO) as log:
                eeg_receiver.main()
            self.assertEqual(connect.call_count, 2)
            self.assertIn("packets=1 samples=36", log.getvalue())
            rows = output.read_text().splitlines()
            self.assertEqual(len(rows), 37)
            self.assertTrue(rows[1].startswith("2,"))

    def test_receiver_bounded_connection_failure(self):
        with patch.object(sys, "argv", ["receiver", "--retries", "2", "--retry-delay", "0"]), \
             patch.object(eeg_receiver.socket, "create_connection", side_effect=OSError("offline")) as connect, \
             patch("sys.stdout", new_callable=io.StringIO):
            eeg_receiver.main()
        self.assertEqual(connect.call_count, 3)


if __name__ == "__main__":
    unittest.main()
